### ISSUE TITLE
GET request getting 500 internal server error when using private email's token

### ISSUE THREAD

**Issue by pohzhiee** [NottsCSS/NottCS_Backend#10]
![image](https://user-images.githubusercontent.com/22704923/36471277-dcfa0298-1728-11e8-9cfe-6e187f727687.png)
Was expecting some form of error saying 'You do not have permission to access this domain.' (line 43 of NottCS_Django/azureAD_auth/auth.py)
didn't manage to find any line that resembles that
[ErrorLog.txt](https://github.com/NottsCSS/NottCS_Backend/files/1743401/ErrorLog.txt)

**Comment by cwkang1998** [comment]
8652fc9a1a610e100a615da31463af28e70285c8 fixes this, #9 and #8
